import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (relativePath) => readFileSync(new URL(`../${relativePath}`, import.meta.url), 'utf8')

const model = read('shared/src/main/ets/model/NhDownloadTask.ets')
const schema = read('shared/src/main/ets/storage/LocalDataStore.ets')
const repository = read('shared/src/main/ets/storage/DownloadQueueRepository.ets')
const service = read('shared/src/main/ets/services/DownloadQueueService.ets')
const settingsModel = read('shared/src/main/ets/model/NhDownloadSettings.ets')
const settingsState = read('shared/src/main/ets/state/DownloadSettingsState.ets')
const settingsRepository = read('shared/src/main/ets/storage/DownloadSettingsRepository.ets')
const settingsService = read('shared/src/main/ets/services/DownloadSettingsService.ets')
const settingsPage = read('feature/settings/src/main/ets/pages/SettingsPage.ets')

assert.match(model, /completedPageIndexes: number\[\] = \[\]/)
assert.match(model, /completionJournalPresent: boolean = false/)
assert.match(model, /markPageCompleted\(pageIndex: number\): void/)
assert.match(model, /result\.completedPageIndexes = this\.completedPageIndexes\.slice\(\)/)
assert.match(model, /this\.completedPageIndexes = source\.completedPageIndexes\.slice\(\)/)

assert.match(schema, /completed_page_indexes TEXT/)
assert.match(schema, /ALTER TABLE download_queue ADD COLUMN completed_page_indexes TEXT/)
assert.match(schema, /ensureDownloadQueueCompletedPageIndexesColumn\(store\)/)
assert.match(repository, /completed_page_indexes/)
assert.match(repository, /task\.completionJournalPresent = !rows\.isColumnNull\(completedIndexesColumn\)/)
assert.match(repository, /snapshot\.completionJournalPresent \? JSON\.stringify\(snapshot\.completedPageIndexes\) : null/)

assert.match(service, /const METADATA_SCHEMA: number = 2/)
assert.match(service, /current\.markPageCompleted\(pageIndex\)[\s\S]*?await DownloadQueueService\.persist\(context, current\)/)
assert.match(service, /const journalAllowsPage: boolean =[\s\S]*?task\.hasCompletedPage\(pageIndex\)/)
assert.match(service, /migrateLegacyCompletionJournal\(context, task\)[\s\S]*?reconcileCompletionJournal\(context, task\)/)
assert.match(service, /names\[index\] === `\$\{task\.galleryId\}`/)
assert.match(service, /const extension: string = DownloadQueueService\.normalizedExtension\(value\)/)

const removeStart = service.indexOf('static async remove(')
const removeEnd = service.indexOf('\n  static snapshot()', removeStart)
const removeBody = service.slice(removeStart, removeEnd)
assert.ok(removeBody.indexOf('await activeRun') < removeBody.indexOf('DownloadQueueRepository.remove'))
assert.ok(removeBody.indexOf('DownloadQueueRepository.remove') < removeBody.indexOf('removeTaskFiles'))
assert.ok(removeBody.indexOf('removeTaskFiles') < removeBody.indexOf('removeFromState'))
assert.match(removeBody, /settled\.completedPages = DownloadQueueService\.completedFileCount/)

assert.match(service, /delayWhileExecutionActive\(galleryId, token, remainMs\)/)

assert.match(settingsModel, /hideFromMediaLibrary: boolean = true/)
assert.match(settingsModel, /result\.hideFromMediaLibrary = this\.hideFromMediaLibrary/)
assert.match(settingsState, /@Trace hideFromMediaLibrary: boolean = true/)
assert.match(settingsState, /this\.hideFromMediaLibrary = settings\.hideFromMediaLibrary/)
assert.match(settingsRepository, /const HIDE_FROM_MEDIA_LIBRARY_KEY: string = 'hide_from_media_library'/)
assert.match(settingsRepository, /settings\.hideFromMediaLibrary = value === 1/)
assert.match(settingsRepository, /snapshot\.hideFromMediaLibrary \? '1' : '0'/)
assert.match(settingsService, /static async setHideFromMediaLibrary\(/)
assert.match(service, /const NO_MEDIA_MARKER_FILE: string = '\.nomedia'/)
assert.match(service, /static reconcileNoMediaMarkerIfReady\(\): boolean/)
assert.match(service, /DownloadSettingsService\.snapshot\(\)\.hideFromMediaLibrary/)
assert.match(service, /return DownloadQueueService\.reconcileNoMediaMarkerIfReady\(\)/)
assert.match(service, /adoptPublicRootFromTasks\(context, restored\)[\s\S]*?reconcileNoMediaMarkerIfReady\(\)/)
assert.match(settingsPage, /settings_download_hide_from_media_library/)
assert.match(settingsPage, /leadingIcon: \$r\('sys\.symbol\.eye_slash'\)/)
assert.match(settingsPage, /DownloadSettingsService\.setHideFromMediaLibrary/)
assert.match(settingsPage, /DownloadQueueService\.reconcileNoMediaMarkerIfReady\(\)/)

console.log('Download queue integrity contract passed.')
